CREATE TABLE IF NOT EXISTS app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(250)                            NOT NULL,
    last_name  VARCHAR(250)                            NOT NULL,
    email      VARCHAR(254)                            NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS company
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    org_name     VARCHAR(250)                            NOT NULL,
    inn          BIGINT                                  NOT NULL,
    app_user_id  BIGINT                                  NOT NULL,
    created_date DATE                                    NOT NULL,
    CONSTRAINT fk_app_user_id FOREIGN KEY (app_user_id) REFERENCES app_user (id)
);

-- Вставка данных в таблицу app_user
INSERT INTO app_user (first_name, last_name, email)
VALUES ('Luke', 'Skywalker', 'luke.skywalker@starwars.com'),
       ('Leia', 'Organa', 'leia.organa@starwars.com'),
       ('Han', 'Solo', 'han.solo@starwars.com'),
       ('Darth', 'Vader', 'darth.vader@starwars.com'),
       ('Obi-Wan', 'Kenobi', 'obiwan.kenobi@starwars.com');

-- Вставка данных в таблицу company
INSERT INTO company (org_name, inn, app_user_id, created_date)
VALUES ('Rebel Alliance', 1234567890, 1, '2024-07-31'),
       ('Galactic Empire', 2345678901, 2, '2024-07-31'),
       ('Jedi Order', 3456789012, 3, '2024-07-31'),
       ('Sith Order', 4567890123, 4, '2024-07-31'),
       ('Resistance', 5678901234, 5, '2024-07-31'),
       ('First Order', 6789012345, 1, '2024-07-31'),
       ('Trade Federation', 7890123456, 2, '2024-07-31'),
       ('Separatists', 8901234567, 3, '2024-07-31'),
       ('Mandalorian Clan', 9012345678, 4, '2024-07-31'),
       ('Bounty Hunters Guild', 1234567891, 5, '2024-07-31'),
       ('New Republic', 2345678902, 1, '2024-07-31'),
       ('Galactic Senate', 3456789013, 2, '2024-07-31'),
       ('Imperial Remnant', 4567890124, 3, '2024-07-31'),
       ('Sith Eternal', 5678901235, 4, '2024-07-31'),
       ('Jedi Council', 6789012346, 5, '2024-07-31'),
       ('Knights of Ren', 7890123457, 1, '2024-07-31'),
       ('Clone Army', 8901234568, 2, '2024-07-31'),
       ('Droid Army', 9012345679, 3, '2024-07-31'),
       ('Hutt Cartel', 1234567892, 4, '2024-07-31'),
       ('Wookiee Tribe', 2345678903, 5, '2024-07-31');

-- Изменение SEQUENCE на client_seq
-- ALTER SEQUENCE client_id_seq RENAME TO client_seq;