CREATE TABLE app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    first_name VARCHAR(250)                            NOT NULL,
    last_name  VARCHAR(250)                            NOT NULL,
    email      VARCHAR(254)                            NOT NULL,
    CONSTRAINT uq_email UNIQUE (email)
);

CREATE TABLE client
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    org_name         VARCHAR(250)                            NOT NULL,
    inn              VARCHAR(12)                             NOT NULL,
    tenant           VARCHAR(250)                            NOT NULL,
    personal_account BIGINT                                  NOT NULL,
    msisdn           BIGINT                                  NOT NULL,
    vip              BOOLEAN                                 NOT NULL,
    app_user_id      BIGINT                                  NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT fk_app_user_id FOREIGN KEY (app_user_id) REFERENCES app_user (id),
    CONSTRAINT uq_service UNIQUE (tenant, msisdn)
);